# --- STAGE 1: Dependency Install ---
FROM node:20-alpine AS dependency_install
WORKDIR /app

# The original error "npm ci" requires "package-lock.json"
# The fix is to ensure package-lock.json is copied.

COPY package.json ./
# -----------------------------------------------------------------
# FIX: The 'npm ci' command needs the lock file generated by npm.
# Ensure this file exists in your project directory (D:\General Projects\examek-frontstore-storefront).
COPY package-lock.json ./
# -----------------------------------------------------------------

# If you are only using 'npm ci', you might want to exclude 'yarn.lock'
# to keep the context clean, but copying it harmlessly for now.
# COPY yarn.lock ./ 

# Install dependencies using the package-lock.json file
RUN npm ci

# --- STAGE 2: Build Application ---
FROM node:20-alpine AS build
WORKDIR /app

# Copy installed dependencies from the previous stage
COPY --from=dependency_install /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_MEDUSA_URL
ENV NEXT_PUBLIC_MEDUSA_URL=$NEXT_PUBLIC_MEDUSA_URL

# Build the application
RUN npm run build

# --- STAGE 3: Final Production Image ---
# Use a minimal image for production
FROM node:20-alpine AS final
WORKDIR /app

# FIX: Addressing the two warnings about legacy ENV format
ENV NODE_ENV=production
ENV PORT=8000

# Assuming this is a standard web application build (like Next.js/Create React App standalone)
# Adjust these paths if your build output is different.
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public
# Copy necessary runtime node modules (if they are outside the standalone folder)
COPY --from=build /app/node_modules ./node_modules 

EXPOSE 8000

# Start the application
CMD ["node", "server.js"]


# --- ALTERNATIVE OPTION (If you intended to use Yarn) ---
# If you delete the 'package-lock.json' file and change the build logic to use Yarn:
#
# FROM node:20-alpine AS dependency_install_yarn
# WORKDIR /app
# COPY package.json ./
# COPY yarn.lock ./
# RUN npm install -g yarn  # Install Yarn globally in the container
# RUN yarn install --frozen-lockfile
#
# You would then need to change STAGE 2 and 3 to copy from 'dependency_install_yarn'.